services:
  # Development services
  postgres:
    image: ankane/pgvector:latest
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: recall
      POSTGRES_PASSWORD: "sOxlqQs6OuZOMbgxOWnAOXQkSUzoWuCE"
    volumes:
      - recall_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "6kKdeBqJxkRK64lqI50Zqwd2bABpR3Mg"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: ankane/pgvector:latest
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: recall_test
      POSTGRES_PASSWORD: "ch3mE8RBveT19lF7uOwyRlENlknXxldJ"
    volumes:
      - recall_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "wiZjitsBg594z24X2Ao4W2I7TumlpWnH"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  recall_data:
  recall_test_data:
