name: recall_client
description: Starting point for a Serverpod client.
version: 0.0.2

environment:
  sdk: '^3.8.0'

dependencies:
  serverpod_auth_idp_client: 3.1.1
  serverpod_auth_client: 3.1.1
  serverpod_client: 3.1.1
